# Generated by Django 5.2.3 on 2025-07-09 06:02

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('dob', models.DateField(blank=True, null=True)),
                ('security_question', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_amount', models.DecimalField(decimal_places=2, default=10000000.0, max_digits=12)),
                ('photo_url', models.ImageField(blank=True, null=True, upload_to='profile_photos/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='cryptoApp.register')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('type', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], default='buy', max_length=4)),
                ('purchased_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='cryptoApp.register')),
            ],
        ),
        migrations.CreateModel(
            name='ProfitLossSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin', models.CharField(max_length=50)),
                ('total_purchased_quantity', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('total_invested', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20)),
                ('total_sold_quantity', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('total_earned', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20)),
                ('holding_quantity', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('current_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20)),
                ('holding_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20)),
                ('net_profit_loss', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profit_loss_summary', to='cryptoApp.register')),
            ],
            options={
                'verbose_name_plural': 'Profit & Loss Summaries',
                'unique_together': {('user', 'coin')},
            },
        ),
        migrations.CreateModel(
            name='TokenBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin', models.CharField(max_length=50)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token_balances', to='cryptoApp.register')),
            ],
            options={
                'unique_together': {('user', 'coin')},
            },
        ),
    ]
