# Generated by Django 5.2.3 on 2025-07-09 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptoApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profitlosssummary',
            name='holding_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profitlosssummary',
            name='total_purchased_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profitlosssummary',
            name='total_sold_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
